### ISSUE TITLE
Try to load mod from base dir and not Mods/ dir

### ISSUE THREAD

**Issue by rennax** [sc2ad/pistol-whip-pc-modloader#2]
Line 94 in ModLoader.cpp 
"auto lib = LoadLibrary(findData.cFileName);"
Will try to load the file from the dir ModLoader.dll is located in, since the cFileName is just the filename and not the path to the file.

**Comment by sc2ad** [comment]
Will look into this later today, thanks!

**Comment by sc2ad** [comment]
Should be fixed in the latest commit of master: `d3d87cbf2399ab67ae4542331034d60d0e94a1ca` feel free to reopen this if that is not the case!
